/*
 * Rubus is an application level protocol for video and audio streaming and
 * the client and server reference implementations.
 * Copyright (C) 2024 Yegore Vlussove
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package backend;

import common.net.request.RubusRequestType;

/**
 * RequestParserStrategy describes the interface the client uses to parse a rubus request. An instance of
 * RequestParserStrategy can be reused to parse different requests, without a necessity to create a new object to
 * parse a different request.
 */
public interface RequestParserStrategy {

	/**
	 * Feeds a new request to this object. The previous state of this object generated by the previous invocation is
	 * to be erased unless the concrete implementation says otherwise.
	 * @param request a new request to parse
	 */
	void feed(String request);

	/**
	 * Returns the type of the request.
	 * @return the request type
	 * @throws IllegalArgumentException if the request doesn't contain the request type
	 */
	RubusRequestType type();

	/**
	 * Returns the value of the specified key the request contains.
	 * @param key the key value of which needs to be returned
	 * @return the value
	 * @throws IllegalArgumentException if the request doesn't contain the key
	 */
	String value(String key);

	/**
	 * Constructs a new instance of RequestParserStrategy by prototyping the concrete implementation of this interface.
	 * @return a new instance of RequestParserStrategy
	 */
	RequestParserStrategy clone();
}
